/**
 * Client-side raster image → SVG tracer for flat/simple logos.
 *
 * Uses canvas-based Otsu thresholding + run-length contour tracing.
 * Accepts PNG, JPG, WebP (traced) and SVG (passed through).
 */

/**
 * Loads a File/Blob as an HTMLImageElement.
 */
function loadImage(file: File): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const url = URL.createObjectURL(file);
    const img = new Image();
    img.onload = () => {
      URL.revokeObjectURL(url);
      resolve(img);
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error('Failed to load image'));
    };
    img.src = url;
  });
}

/**
 * Converts a File into canvas ImageData, scaled to fit within maxDim.
 */
async function fileToImageData(
  file: File,
  maxDim: number = 512,
): Promise<ImageData> {
  const img = await loadImage(file);

  // Scale down if needed, preserving aspect ratio
  const scale = Math.min(maxDim / img.width, maxDim / img.height, 1);
  const w = Math.round(img.width * scale);
  const h = Math.round(img.height * scale);

  const canvas = document.createElement('canvas');
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext('2d')!;

  // White background for images with transparency → avoids transparent-to-black artifacts
  ctx.fillStyle = '#FFFFFF';
  ctx.fillRect(0, 0, w, h);
  ctx.drawImage(img, 0, 0, w, h);

  return ctx.getImageData(0, 0, w, h);
}

/**
 * Sanitises an SVG string for safe DOM insertion:
 * strips <script>, event handlers, and external references.
 */
function sanitizeSvg(svg: string): string {
  return svg
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/\bon\w+\s*=\s*"[^"]*"/gi, '')
    .replace(/\bon\w+\s*=\s*'[^']*'/gi, '');
}

/**
 * Returns true if a hex colour string is white-ish (very close to #FFFFFF).
 */
function isWhitish(hex: string): boolean {
  const cleaned = hex.replace(/^#/, '');
  if (cleaned.length === 3) {
    const r = parseInt(cleaned[0] + cleaned[0], 16);
    const g = parseInt(cleaned[1] + cleaned[1], 16);
    const b = parseInt(cleaned[2] + cleaned[2], 16);
    return r >= 240 && g >= 240 && b >= 240;
  }
  if (cleaned.length === 6) {
    const r = parseInt(cleaned.slice(0, 2), 16);
    const g = parseInt(cleaned.slice(2, 4), 16);
    const b = parseInt(cleaned.slice(4, 6), 16);
    return r >= 240 && g >= 240 && b >= 240;
  }
  return false;
}

/**
 * Normalises a colour value like "white", "rgb(255,255,255)", "#fff" to a
 * hex string, or returns the original value if unrecognised.
 */
function normalizeColor(val: string): string {
  const trimmed = val.trim().toLowerCase();
  if (trimmed === 'white' || trimmed === '#fff' || trimmed === '#ffffff') return '#ffffff';
  if (trimmed === 'none' || trimmed === 'transparent') return trimmed;
  // rgb(…)
  const rgbMatch = trimmed.match(/^rgb\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)/);
  if (rgbMatch) {
    const hex = [rgbMatch[1], rgbMatch[2], rgbMatch[3]]
      .map(n => parseInt(n, 10).toString(16).padStart(2, '0'))
      .join('');
    return `#${hex}`;
  }
  return trimmed;
}

/**
 * Strips white/near-white background elements from an SVG so it renders with
 * a transparent background.  Removes:
 * - <rect> elements that span the full SVG viewport and have a white-ish fill.
 * - <path> elements with a white-ish fill that is the first child (often the
 *   background path generated by image tracers).
 */
function stripSvgBackground(svg: string): string {
  try {
    const parser = new DOMParser();
    const doc = parser.parseFromString(svg, 'image/svg+xml');
    const svgEl = doc.querySelector('svg');
    if (!svgEl) return svg;

    // Determine SVG dimensions (for comparing rect sizes)
    const vb = svgEl.getAttribute('viewBox');
    let svgW = parseFloat(svgEl.getAttribute('width') || '0');
    let svgH = parseFloat(svgEl.getAttribute('height') || '0');
    if (vb) {
      const parts = vb.trim().split(/[\s,]+/).map(Number);
      if (parts.length === 4) {
        svgW = svgW || parts[2];
        svgH = svgH || parts[3];
      }
    }

    // Remove background <rect>s
    svgEl.querySelectorAll('rect').forEach(rect => {
      const fill = normalizeColor(
        rect.getAttribute('fill') || rect.style.fill || '#000000'
      );
      if (!isWhitish(fill)) return;

      const rw = parseFloat(rect.getAttribute('width') || '0');
      const rh = parseFloat(rect.getAttribute('height') || '0');
      const rx = parseFloat(rect.getAttribute('x') || '0');
      const ry = parseFloat(rect.getAttribute('y') || '0');

      // Must roughly cover the full viewport
      if (
        svgW > 0 && svgH > 0 &&
        rx <= 1 && ry <= 1 &&
        rw >= svgW * 0.95 && rh >= svgH * 0.95
      ) {
        rect.remove();
      }
    });

    // Remove the very first <path> if it has a white-ish fill
    // (common output from image tracers as background)
    const firstPath = svgEl.querySelector('path');
    if (firstPath) {
      const fill = normalizeColor(
        firstPath.getAttribute('fill') || firstPath.style.fill || ''
      );
      if (isWhitish(fill)) {
        firstPath.remove();
      }
    }

    return new XMLSerializer().serializeToString(svgEl);
  } catch {
    // If parsing fails, return as-is
    return svg;
  }
}

/**
 * Flattens an SVG to monochrome black with transparent background.
 * - Forces all fill and stroke colours to #000000 (except none/transparent).
 * - Removes <defs> children that won't render in monochrome (linearGradient,
 *   radialGradient, filter, clipPath, mask, pattern).
 * - Removes inline `style` colour properties in favour of explicit attributes.
 * - Strips embedded <style> blocks (class-based styling won't survive flattening).
 * - Removes white-ish elements (likely backgrounds).
 */
function flattenSvgToMonochrome(svg: string): string {
  try {
    const parser = new DOMParser();
    const doc = parser.parseFromString(svg, 'image/svg+xml');
    const svgEl = doc.querySelector('svg');
    if (!svgEl) return svg;

    // Remove <style> blocks — we'll set colours directly on elements
    svgEl.querySelectorAll('style').forEach(s => s.remove());

    // Remove complex paint-server and filter definitions
    const removableDefs = 'linearGradient, radialGradient, filter, clipPath, mask, pattern';
    svgEl.querySelectorAll(removableDefs).forEach(el => el.remove());

    // Clean up references that pointed to now-removed defs
    const urlRefAttrs = ['fill', 'stroke', 'clip-path', 'mask', 'filter'];

    // Shape/text elements that can have fill/stroke
    const paintable = svgEl.querySelectorAll(
      'path, polygon, polyline, circle, ellipse, rect, line, text, tspan, g, use'
    );

    paintable.forEach(el => {
      const htmlEl = el as SVGElement;

      // Process each paintable attribute
      for (const attr of ['fill', 'stroke']) {
        // Check inline style first, then attribute
        const styleVal = htmlEl.style.getPropertyValue(attr);
        const attrVal = el.getAttribute(attr);
        const raw = styleVal || attrVal || '';
        const norm = normalizeColor(raw);

        // Clear inline style colour props — we use attributes only
        if (styleVal) htmlEl.style.removeProperty(attr);

        if (norm === 'none' || norm === 'transparent') {
          // Keep as-is — intentionally unfilled/unstroked
          continue;
        }

        if (raw.startsWith('url(')) {
          // Referenced a gradient/pattern that was removed → make black
          el.setAttribute(attr, '#000000');
          continue;
        }

        if (norm && norm !== '') {
          // Has a colour → check if white-ish first
          if (isWhitish(norm)) {
            // White fills become transparent (background removal)
            el.setAttribute(attr, 'none');
          } else {
            // Any other colour → force to black
            el.setAttribute(attr, '#000000');
          }
        }
      }

      // Remove now-broken url() references on other attributes
      for (const attr of urlRefAttrs.slice(2)) { // clip-path, mask, filter
        const val = el.getAttribute(attr);
        if (val && val.startsWith('url(')) {
          el.removeAttribute(attr);
        }
      }

      // Clean up opacity/fill-opacity/stroke-opacity — keep them so
      // relative opacity within the logo is preserved
      // Remove class attributes since <style> blocks are gone
      if (el.hasAttribute('class')) {
        el.removeAttribute('class');
      }
    });

    // If the root <g> or first <g> has white fill, handle it
    // (some SVGs set fill on a parent <g>)

    return new XMLSerializer().serializeToString(svgEl);
  } catch {
    return svg;
  }
}

/**
 * Lightweight canvas-based raster → SVG tracer for flat logos.
 *
 * 1. Converts to grayscale.
 * 2. Applies Otsu threshold to separate foreground (dark) from background (white).
 * 3. Encodes foreground pixels as horizontal run-length SVG path commands.
 * 4. Returns an SVG string with a single black <path>.
 */
function traceImageDataToSvg(imageData: ImageData): string {
  const { width, height, data } = imageData;

  // ── Step 1: Grayscale + binary grid ───────────────────────────────────
  const gray = new Uint8Array(width * height);
  for (let i = 0; i < gray.length; i++) {
    const r = data[i * 4];
    const g = data[i * 4 + 1];
    const b = data[i * 4 + 2];
    gray[i] = Math.round(0.299 * r + 0.587 * g + 0.114 * b);
  }

  // Otsu's method for automatic threshold
  const histogram = new Array(256).fill(0);
  for (let i = 0; i < gray.length; i++) histogram[gray[i]]++;

  let total = gray.length;
  let sum = 0;
  for (let i = 0; i < 256; i++) sum += i * histogram[i];

  let sumB = 0, wB = 0, wF = 0, maxVariance = 0, threshold = 128;
  for (let t = 0; t < 256; t++) {
    wB += histogram[t];
    if (wB === 0) continue;
    wF = total - wB;
    if (wF === 0) break;
    sumB += t * histogram[t];
    const mB = sumB / wB;
    const mF = (sum - sumB) / wF;
    const variance = wB * wF * (mB - mF) * (mB - mF);
    if (variance > maxVariance) {
      maxVariance = variance;
      threshold = t;
    }
  }

  // Binary grid: 1 = foreground (dark), 0 = background (white)
  const binary = new Uint8Array(width * height);
  for (let i = 0; i < gray.length; i++) {
    binary[i] = gray[i] <= threshold ? 1 : 0;
  }

  // ── Step 2: Trace contours via row run-length encoding → SVG path ────
  // Encode each horizontal run of foreground pixels as a rect-shaped path
  // command. This produces clean output for flat logos.
  const paths: string[] = [];
  for (let y = 0; y < height; y++) {
    let x = 0;
    while (x < width) {
      if (binary[y * width + x] === 1) {
        const startX = x;
        while (x < width && binary[y * width + x] === 1) x++;
        // Horizontal run from startX to x-1 on row y
        paths.push(`M${startX},${y}h${x - startX}v1h${-(x - startX)}z`);
      } else {
        x++;
      }
    }
  }

  const svgPath = paths.join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><path d="${svgPath}" fill="#000000" stroke="none"/></svg>`;
}

/**
 * Trace a raster image File to an SVG string.
 *
 * - If the file is already SVG, it's returned (sanitised) as-is.
 * - Otherwise, the image is loaded onto a canvas, thresholded, and traced.
 *
 * @param file  The image file (PNG, JPG, WebP, or SVG).
 * @param opts  Optional overrides for the tracer.
 * @returns     A promise resolving to the SVG markup string.
 */
export async function traceImageToSvg(
  file: File,
  opts?: {
    numberOfColors?: number;
    transparentBackground?: boolean;
  },
): Promise<string> {
  // ── SVG pass-through ───────────────────────────────────────────────────
  if (file.type === 'image/svg+xml' || file.name.toLowerCase().endsWith('.svg')) {
    const raw = await file.text();
    const sanitized = sanitizeSvg(raw);
    const stripped = stripSvgBackground(sanitized);
    return flattenSvgToMonochrome(stripped);
  }

  // ── Raster → SVG tracing (canvas-based, no external dependency) ──────
  const imageData = await fileToImageData(file, 512);

  const svgString = traceImageDataToSvg(imageData);

  const sanitizedSvg = sanitizeSvg(svgString);
  const stripped = stripSvgBackground(sanitizedSvg);
  return flattenSvgToMonochrome(stripped);
}

/**
 * Estimate the byte size of an SVG string (UTF-8).
 */
export function svgByteSize(svg: string): number {
  return new Blob([svg]).size;
}
