import { ScheduledTimeChange } from '../App';
import { parseLocalDate } from './dateUtils';

/**
 * Check if a scheduled time change should show an announcement
 * Returns true only if the change starts tomorrow (1 day away).
 * Once the start date arrives, the iqama times already reflect the new time.
 */
function shouldShowAnnouncement(change: ScheduledTimeChange): boolean {
  const now = new Date();
  // Use parseLocalDate to avoid UTC midnight shift (new Date("YYYY-MM-DD") is UTC)
  const startDate = parseLocalDate(change.startDate);
  
  // Set to start of day for comparison
  now.setHours(0, 0, 0, 0);
  startDate.setHours(0, 0, 0, 0);
  
  const diffMs = startDate.getTime() - now.getTime();
  const diffDays = diffMs / (1000 * 60 * 60 * 24);
  
  // Show announcement if change is happening tomorrow (1 day away)
  // Once the start date arrives, the iqama times already reflect the change — no reminder needed
  return diffDays === 1;
}

export interface AutoGeneratedAnnouncement {
  prayer: 'fajr' | 'dhuhr' | 'asr' | 'maghrib' | 'isha' | 'jumuah';
  newTime: string;
  startDate: string;
  reason?: string;
  daysUntil: number; // 1 = tomorrow (only value now)
}

/**
 * Get auto-generated announcements for scheduled time changes
 * Returns announcements only for changes happening tomorrow
 */
export function getAutoAnnouncements(
  scheduledChanges: ScheduledTimeChange[] | undefined
): AutoGeneratedAnnouncement[] {
  if (!scheduledChanges || scheduledChanges.length === 0) {
    return [];
  }

  const now = new Date();
  now.setHours(0, 0, 0, 0);

  return scheduledChanges
    .filter(change => shouldShowAnnouncement(change))
    .map(change => {
      // Use parseLocalDate to avoid UTC midnight shift
      const startDate = parseLocalDate(change.startDate);
      startDate.setHours(0, 0, 0, 0);
      
      const diffMs = startDate.getTime() - now.getTime();
      const daysUntil = Math.round(diffMs / (1000 * 60 * 60 * 24));

      return {
        prayer: change.prayer,
        newTime: change.newTime,
        startDate: change.startDate,
        reason: change.reason,
        daysUntil
      };
    });
}

/**
 * Format the auto-announcement message for display
 */
export function formatAnnouncementMessage(announcement: AutoGeneratedAnnouncement): string {
  const prayerNames = {
    fajr: 'Fajr',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
    jumuah: 'Jumuah'
  };

  const prayerName = prayerNames[announcement.prayer];
  const timing = 'Starting tomorrow';
  const reason = announcement.reason ? ` (${announcement.reason})` : '';

  return `${timing}: ${prayerName} iqama time changes to ${announcement.newTime}${reason}`;
}